version: 2
jobs:
  test-3.8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install --user -e .[tests]
      - run:
          command: |
            make flake8
            make tests

workflows:
  version: 2
  default:
    jobs:
      - test-3.8
