version: 2
jobs:
  test-3.6:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv venv; . venv/bin/activate; make develop
      - run:
          command: |
            . venv/bin/activate; make tests

workflows:
  version: 2
  default:
    jobs:
      - test-3.6
